Android Release 13

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -994,24 +994,36 @@ definitions:
         # Extract CODE_SIGN_IDENTITY
         CODE_SIGN_IDENTITY=$(security find-identity -v -p codesigning "$KEYCHAIN_NAME" | awk '{print $2}' | head -n 1)
         echo "CODE_SIGN_IDENTITY=$CODE_SIGN_IDENTITY"
-
+        if [ -z "$CODE_SIGN_IDENTITY" ]; then
+        echo "❌ Failed to extract CODE_SIGN_IDENTITY"
+        exit 1
+        fi
+        
+        
         # Update iOS deployment target
         echo "🔧 Updating iOS deployment target to 13.0 in Podfile..."
         sed -i '' 's/platform :ios, .*/platform :ios, "13.0"/' ios/Podfile
 
         # CocoaPods setup
         echo "🛠️ Installing CocoaPods..."
+        
+        # Clean Flutter and CocoaPods caches
         flutter clean
         rm -rf ios/Pods ios/Podfile.lock ~/Library/Caches/CocoaPods ~/.cocoapods/repos
-        sudo gem install cocoapods || true
-        cd ios
-        pod install --repo-update
-        cd ..
+        
+        # Install CocoaPods and required Ruby gem
+        set -x
+        gem install cocoapods --pre --silent
+        gem install securerandom -v 0.3.2 --silent
+        
+        # Install iOS dependencies via CocoaPods
+        pod install --project-directory=ios
+        
+        # Restore Flutter dependencies
         flutter pub get
-
-        # Generate iOS build files (without codesigning yet)
+        
+        # Generate iOS build files without code signing
         flutter build ios --release --no-codesign
-
         # Archive the app
         echo "📦 Archiving app with code signing..."
         xcodebuild -workspace ios/Runner.xcworkspace \
@@ -1026,7 +1038,7 @@ definitions:
           PROVISIONING_PROFILE_SPECIFIER="$UUID" \
           PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
           CODE_SIGN_IDENTITY="$CODE_SIGN_IDENTITY" \
-          OTHER_CODE_SIGN_FLAGS="--keychain $KEYCHAIN_NAME" \
+          OTHER_CODE_SIGN_FLAGS="--keychain ~/Library/Keychains/$KEYCHAIN_NAME-db"  \
           archive
 
         # ExportOptions.plist
@@ -1720,6 +1732,8 @@ workflows:
       vars:
         XCODE_WORKSPACE: "Runner.xcworkspace"
         XCODE_SCHEME: "Runner"
+        LANG: en_US.UTF-8
+        LC_ALL: en_US.UTF-8
       flutter: stable
       xcode: latest
       cocoapods: default
