Android Release 09

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -1603,30 +1603,32 @@ workflows:
           echo "🛠️ Setting UTF-8 encoding for CocoaPods..."
           export LANG=en_US.UTF-8
           export LC_ALL=en_US.UTF-8
-
+          
           echo "💻 Shell in use: $SHELL"
           echo "🌍 Current language: $LANG"
-
-          # Clean up old Pod configurations
+          
+          # Clean up old Pod configurations and Flutter cache
           echo "🧹 Cleaning up CocoaPods and Flutter cache..."
           flutter clean
           rm -rf ios/Pods ios/Podfile.lock ~/Library/Caches/CocoaPods ~/.cocoapods/repos
-
+          
           # Update CocoaPods
           echo "🚀 Installing/Updating CocoaPods..."
           sudo gem install cocoapods
-
+          
           # Reinstall pods and update the repo
           echo "🔄 Reinstalling CocoaPods dependencies..."
-          cd ios
+          cd ios || exit
+          pod reintegrate
           pod install --repo-update
           cd ..
-
+          
           # Final cleanup and dependency fetch
           echo "🔧 Final cleanup and fetching dependencies..."
           flutter clean
+          xcodebuild clean
           flutter pub get
-
+        
           echo "✅ Pod update complete. CocoaPods version: $(pod --version)"
        
       
